### ISSUE TITLE
Formula not following requirements

### ISSUE THREAD

**Issue by faminee** [gytdau/password#1]
Most websites have a requirement of 8letters, etc. You will need to make the password formula longer.

**Comment by gytdau** [comment]
To solve this issue, I added nouns as a possible password ingredient, using [this list](http://www.desiquintans.com/nounlist) as my source. The number of ingredients has also been increased from 3 to 4. This should hopefully make most formulas pass the 8 character mark.

Thanks for reporting this issue, @MrWhiteGoat :grinning:

**Comment by faminee** [comment]
Np boi.
